### ISSUE TITLE
Double check all images are rendering correctly

### ISSUE THREAD

**Issue by bogreudell** [wikitongues/wikitongues-website#14]
Some are echoed in the background style of divs and other elements. This is to make them crop more easily (hint: user background-size:cover;)

**Comment by bogreudell** [comment]
- Video alert is rendering correctly, as long as the video post in question has a featured image. Same goes for featured items (videos)
- Homepage primary sections are working fine
- Featured blog posts (recent News) **wasn't** working, so I circumvented this by adding a custom field to the news item post type. Will explain and help you set up during our next call

**Comment by robinmetral** [comment]
I opened a PR for this, already fixed the member background-images.

Will continue working on that branch after you tell me about the featured blog posts issue on our call, @bogreudell!
