### ISSUE TITLE
Double check projects post type is rendering on Projects page 

### ISSUE THREAD

**Issue by bogreudell** [wikitongues/wikitongues-website#15]

**Comment by bogreudell** [comment]
@robinmetral this is working fine, you just need to populate the content in the CMS (Pages > Projects). Let me know if you run into any trouble :)

**Comment by robinmetral** [comment]
Great!

Just a couple comments:

- Are there no project type posts on the dev site? The dropdown in *Featured Projects* doesn't show anything
- I tried to add a Page Introduction Header to the page but got the error `Banner Image value is required` in *Donate Banner*. Is there supposed to be a donate banner on this page?
