### ISSUE TITLE
Make sure video post type links to YouTube

### ISSUE THREAD

**Issue by bogreudell** [wikitongues/wikitongues-website#16]

**Comment by robinmetral** [comment]
These are still linking to a post page on my end :slightly_frowning_face:

**Comment by bogreudell** [comment]
Oh, I see the issue. The thumbnails are wrapped in a link that points to youtube, but the excerpts still have that "view article" link. This is a new issue for me to resolve, so I'll create a new ticket for this. In the meantime, let's just disregard and charge ahead
