### ISSUE TITLE
How to style the nav sub-links?

### ISSUE THREAD

**Issue by robinmetral** [wikitongues/wikitongues-website#2]
I see that `<?php main_nav(); ?>` in `header.php` generates a list with a sub-links for secondary links (namely "Leadership", "Community" and "Supporters" under "Who We Are").

![screenshot_2018-08-12 partners wikitongues org](https://user-images.githubusercontent.com/35560568/44000156-2dae33c8-9e45-11e8-9400-0be18b003dfb.png)

However these do not appear in the Mockups. Are they displayed on hover?

If they are, how do you want them styled? A dropdown?

**Comment by bogreudell** [comment]
Each list item in the "dropdown" should stack beneath the parent list item. I don't think it needs to be more styled beyond that. Perhaps we'll want a slight typographic indicator that these are child items but we'll cross that bridge when the time comes :)
