### ISSUE TITLE
Warning: array_merge(): argument #1 is not an array

### ISSUE THREAD

**Issue by robinmetral** [wikitongues/wikitongues-website#3]
On the [Supporters](https://user-images.githubusercontent.com/35560568/44084344-a721491a-9fe0-11e8-927b-2d4888f9cc6c.png) page (Tier 3 donors section), this PHP error message appears:

`Warning: array_merge(): argument #1 is not an array in template-donors.php on line 83`

**Comment by bogreudell** [comment]
This array merge seems to be working on my local instance. Is it still a problem for you or can I close the issue? :)

**Comment by robinmetral** [comment]
Great! However I merged locally and still get the error - is that normal @bogreudell?

**Comment by bogreudell** [comment]
It is not! We may have to look at this together to see what's going on. For the to-do list! Since the styles are pretty much the same however, we shouldn't be too stressed :)

**Comment by robinmetral** [comment]
So we're ingnoring this for now as it can't be replicated.
Probably a bug with my instance of the dev site :slightly_smiling_face:
