### ISSUE TITLE
Hide alert section details on mobile

### ISSUE THREAD

**Issue by robinmetral** [wikitongues/wikitongues-website#39]
@bogreudell how do we want the alert section to display on mobile?

On desktop there are roughly two columns: the image on the left, and a column with the text on the right.

On mobile, the text reduced to only 50% width could take almost a full screen's height:

![capture du 2018-10-05 11-19-47](https://user-images.githubusercontent.com/35560568/46515903-c9208e80-c890-11e8-8102-e3e06197d652.png)

I think we can either:

1. choose to place the image above the text
2. choose to show only the text's heading on mobile, and hide the details:
  ![capture du 2018-10-05 11-21-02](https://user-images.githubusercontent.com/35560568/46515914-da699b00-c890-11e8-8201-98289a4b5449.png)

**Comment by bogreudell** [comment]
I would opt for hiding the details and showing only the heading. The smaller the screen, the more ruthless we need to be with cutting content :)
